### ISSUE TITLE
Move from react and redux to just plain JS

### ISSUE THREAD

**Issue by tnguyen14** [tnguyen14/ledge#16]
- [x] render form
- [x] render transactions
- [x] render stats
- [x] form submit event
- [x] clear form after submit (#11)
- [x] form validation
- [x] transaction edit
- [x] transaction delete
- [x] update stat on transaction change
- [x] update row display on transaction change
- [x] merchant autofill
- [x] load more weeks
- [x] update account stats for any transaction changes (might wanna consider pushing all data to a global state)
- [x] remove the `2` suffix

**Comment by tnguyen14** [comment]
use eventemitter (https://github.com/primus/eventemitter3) to trigger add/ update event from form to transactions.

**Comment by tnguyen14** [comment]
use https://github.com/substack/node-deep-equal and https://github.com/flitbit/diff to update each transaction at a detailed level to avoid losing event listeners.
